name: Test Project
on: push
jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Run Linters
        uses: wearerequired/lint-action@v2
      
